env = XCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_THEME,Bibata-Modern-Ice

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

plugin:dynamic-cursors {
    enabled = true
    mode = none  # отключает эффекты наклона/вращения

    shake {
        enabled = true
        threshold = 4.0
        # увеличение курсора
        base = 3.0

        # время удержания увеличенного курсора (мс)
        timeout = 2000

        # не показывать прочие эффекты
        effects = false
    }
}

dwindle {
    #pseudotile = true # Master switcfor pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false 
}

render {
	new_render_scheduling = true
}

#################SOURCE#############################
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/animation.conf
source = ~/.config/hypr/config/borders.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/input.conf
