exec-once = hyprpm enable dynamic-cursors
exec-once = awww-daemon
exec-once = swaync
exec = waybar &
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hypridle
exec-once = blueman-applet
exec-once = wl-paste --watch cliphist store
exec-once = hyprsession
